# Supabase Configuration for WalkAboutSD

[project]
id = "your-project-id"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "auth"]
max_rows = 1000

[db]
port = 54322
pool_size = 100

[storage]
file_size_limit = "50MiB"

[auth]
enable_signup = true
enable_anonymous_sign_ins = false

[auth.email]
enable_confirmations = true
enable_signup = true
double_confirm_changes = true
template.confirmation = "Welcome to WalkAboutSD! Please confirm your email."
template.magic_link = "Your magic link for WalkAboutSD"
template.invite = "You've been invited to WalkAboutSD"

[auth.sms]
enable_signup = false
enable_confirmations = false

[auth.external.google]
enabled = true
client_id = "env(GOOGLE_CLIENT_ID)"
secret = "env(GOOGLE_CLIENT_SECRET)"

[studio]
enabled = true
port = 54323